### ISSUE TITLE
LOC-23 ⁃ Version inconsistency between cdk and cdklocal

### ISSUE THREAD

**Issue by karin-jsq** [localstack/aws-cdk-local#3]
While testing cdklocal, we found some inconsistencies.  Despite having cdk installed (and pegged to version 1.67.0), it seems that cdk and cdk-local's cdk versions are out of sync

```
root@ea857e43d7ef:/usr/local/src# cdk --version
1.67.0 (build 2b4dd71)
root@ea857e43d7ef:/usr/local/src# cdklocal --version
1.69.0 (build 2b474b9)
```

I thought i might have been related to how we install cdk, `npm install -g cdk@1.67.0`, so i changed it to `npm install -g aws-cdk@1.67.0`. That made no difference.

For context, we have a docker-compose.yml that includes:

```
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudformation,ec2,iam,lambda,rds,s3,secretsmanager,sqs
      - DEBUG=${DEBUG-True}
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-west-2
    volumes:
      - "./build/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

We have another defined docker service that installs all our cdk requirements (npm and python) and where the code lives and is then executed.

There are other issues that are blocking us currently (#1), but having version inconsistencies is odd.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-23) by [Unito](https://www.unito.io/learn-more)

**Comment by jackmcguire1** [comment]
I am not having this issue, I am on 1.70.0

**Comment by miho120** [comment]
Hi @karin-jsq !
This inconsistency caused the way that npm installs the dependencies (and it's not friendly to global packages at all). `cdklocal` is only a wrapper and it actually only `require  aws-cdk` with some pre-executed node code and not calling installed binary. Furthermore, to be sure that this `aws-cdk` library is installed we added it to dependencies and npm installs this dependency in aws-cdk-local package folder (latest available version).

So, if you want to use already installed global `aws-cdk`package you need to link it first to the aws-cdk-local package. There is a workaround that should solve your problem:

1. Just in case uninstall global aws-cdk-local: `npm uninstall -g aws-cdk-local`
2. Clone the aws-cdk-local repo (don't install with npm and make sure that there is no `node_modules` folder inside cloned repo).
3. Navigate to the cloned repo
4. I assume that at this step you have already installed global `npm install -g aws-cdk@1.67.0` as you wrote.
5. Then run:
```bash
$ npm link
$ npm link aws-cdk
$ npm install -g ./
```
This will install aws-cdk-local as a global package and `cdklocal` will be stuck to your aws-cdk global version.

@karin-jsq please let me know if this helped you.

P.S. But there might be another solution from our side if we'll stick `aws-cdk-local` version to the `aws-cdk` version. I mean we might trigger `aws-cdk-local` build and release when the new version of `aws-cdk` is available. This approach will prevent such inconsistency. What do you think @whummer ?

**Comment by whummer** [comment]
Thanks for providing this explanation and solution/workaround @jackmcguire1 . Does this work for your use case @karin-jsq @jackmcguire1 ?

As @miho120 mentioned, `cdklocal` is only a small wrapper script, and under the covers any version of the cdk library can be used. By default, we install the latest version of `aws-cdk` as well (to make the script usable out of the box after installing `npm install aws-cdk-local`), but in the future we may actually remove the dependency to `aws-cdk` in `package.json` altogether, to avoid any confusion with different installed versions. Thanks
