### ISSUE TITLE
ERROR: Non-whitespace before first tag

### ISSUE THREAD

**Issue by jonashdown** [localstack/aws-cdk-local#33]
Hi,

When running `cdklocal deploy` I get the above error, which suggests there's something trying to parse XML

further info:
```
Line: 0
Column: 1
Char: {
Found errors
``` 

It also looks like the error is coming from code generated by cdklocal deploy

**Comment by whummer** [comment]
Thanks for reporting @jonashdown - can you please provide a small code snippet of your CDK example, to help us reproduce this issue..? Thanks

**Comment by arunzone** [comment]
I too got the same problem, in my case the sample code is 
```
export class CloudStoresCdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, posEnv: string, props?: cdk.StackProps) {
    super(scope, id, props);


    // import exisitng VPC
    const existingVpc = this.getExistingVPC();

  }

  public getExistingVPC(): ec2.IVpc {
    return ec2.Vpc.fromLookup(this, 'VPC', {isDefault: false});
  }

}
```

**Comment by whummer** [comment]
Thanks for the update @arunzone . Can you please share some more details about your environment, and the error message you're seeing? Thanks

Just did a quick test deploying your sample code against the `latest` LocalStack Docker image - seems to be working:
```
$ awslocal ec2 create-vpc --cidr-block 161.0.0.1/24
...
$ cdklocal deploy
AppStack: deploying...
AppStack: creating CloudFormation changeset...

 ✅  AppStack

Stack ARN:
arn:aws:cloudformation:eu-central-1:000000000000:stack/AppStack/5aba1701
```

**Comment by michaelgmcd** [comment]
@jonashdown Not sure if you're still running into this, but the issue for me was not having the proper services running (via the `SERVICES` environment variable) in my localstack instance. In this case, make sure you have `ec2` included.

**Comment by dominikschubert** [comment]
Closing stale issue. 

FYI: The `SERVICES` variable is not needed anymore and services are loaded lazily by default.
