### ISSUE TITLE
CDK Toolkit bucket URL is wrong for large template files

### ISSUE THREAD

**Issue by AminFazlMondo** [localstack/aws-cdk-local#41]
When a stack getting big, the cloudformation template gets deployed to cdk toolkit bucket and then the url used for cloudformation. AWS-CDK-local does not work under this circumstance, as the bucket URL is not constructed correctly.

Previously that was addressed by the following piece of code

```
Object.defineProperty(ToolkitInfo.prototype, 'bucketUrl', {
  get() {
    const bucket = this.requireOutput(BUCKET_NAME_OUTPUT);
    const domain = this.requireOutput(BUCKET_DOMAIN_NAME_OUTPUT) || getLocalHost();
    return `https://${domain.replace(`${bucket}.`, '')}/${bucket}`
  }
});
```

But the newer version of CDK has changed the implementation of "ToolkitInfo" class to be an abstract class which has been implemented by "ExistingToolkitInfo". [see](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/toolkit-info.ts)

Unfortunately "ExistingToolkitInfo" is not a exported class and it is not accessible to be overriden like the above example.

Another issue is the bucketUrl should include the port number (4566) for it to work.

**Comment by whummer** [comment]
Thanks for reporting @AminFazlMondo - do you think you can share a small example that helps us replicate this issue? 

Taking a first look at the implementation, it seems that we may be able to patch `ToolkitInfo.lookup` and `ToolkitInfo.fromStack` which are each returning an instance of `ExistingToolkitInfo`. 

Do you think you could help out with an initial PR to patch this functionality - that would be highly appreciated! Thanks for your help.
