### ISSUE TITLE
Unable to run CDK local Error: Cannot find module 'aws-cdk/lib/api/aws-auth/sdk-provider'

### ISSUE THREAD

**Issue by rgoodwin** [localstack/aws-cdk-local#45]
Trying to run cdklocal (having used npm to install it) and get the following error:

```
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'aws-cdk/lib/api/aws-auth/sdk-provider'
Require stack:
- /usr/local/lib/node_modules/aws-cdk-local/bin/cdklocal
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/aws-cdk-local/bin/cdklocal:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/aws-cdk-local/bin/cdklocal' ]
}
```
Note: I'm using cdk with python code (but tried running `cdklocal` in an empty directory as well).

**Comment by whummer** [comment]
Thanks for reporting @rgoodwin . Just to confirm - did you install the `aws-cdk` npm package as well? (See README here: https://github.com/localstack/aws-cdk-local#quick-installation). 

Can you please share the output of the following commands:
```
$ node -e 'console.log(require("aws-cdk"))'
$ cdk --version
$ cdklocal --version
```

Thanks!

**Comment by nbraid** [comment]
Not OP, but I ran into this error as well. Seemed to be a versioning issue. 

```
npm install -g aws-cdk-local@1.65.2
npm install -g cdk@1.70.0 
```
seems to work, but earlier (<1.65) or later (>1.90) versions of CDK do not.

**Comment by SimonLdj** [comment]
got similar issue:
```
Error: Cannot find module 'aws-cdk/node_modules/cdk-assets/lib/private/handlers/files'
```
with `"aws-cdk": "1.111.0"` & `"aws-cdk-local": "1.65.5"`
but with `"aws-cdk-local": "1.65.4"` all looks good

**Comment by rubfergor** [comment]
@SimonLdj this seems to be related to the latest change:
`const { FileAssetHandler } = require('aws-cdk/node_modules/cdk-assets/lib/private/handlers/files');`

As a result, anything other than NPM or Yarn (and in yarn, it doesn't work with monorepos will probably fail because node_modules folder doesn't have to exist as folder itself because it can be a symlink (which probably will throw an error).

**Comment by recklessYello** [comment]
Please note I had a similar issue with aws-cdk-local version 1.65.5 
My error was
`cdklocal --version `  
Error Cannot find module diff

Taking @SimonLdj advice solved the issue.

**Comment by ubaidbaig-10p** [comment]
@recklessYello I'm also facing the same issue i.e. Error Cannot find module diff, I have created a pull request to fix the issue, see below:

https://github.com/localstack/aws-cdk-local/pull/49

**Comment by whummer** [comment]
Thanks @SimonLdj @nbraid @rubfergor @recklessYello @ubaidbaig-10p @rgoodwin . We have pushed a small fix which should (hopefully) resolve the import issues. Can you please give it another try with the latest version `aws-cdk-local@1.65.8`. Hope that helps - please report here or create a new issue with more details if the problem persists. Thanks!

**Comment by rubfergor** [comment]
Seems to be working now! Thanks!

**Comment by ethanalef** [comment]
It doesn't work for me too..

![Screenshot 2022-02-25 at 12 56 04 PM](https://user-images.githubusercontent.com/28945328/155656253-b41e4d81-8578-4419-8c2d-68bd3836a036.png)

**Comment by Li-ReDBox** [comment]
Same experience here. Currently:
```
npm -g i aws-cdk@1.111.0 aws-cdk-local@1.65.4
```
