### ISSUE TITLE
Does cdk-local with with python based CDK projects

### ISSUE THREAD

**Issue by rgoodwin** [localstack/aws-cdk-local#54]
Before getting into cdklocal I wanted to confirm it will work with cdk projects that are using python. -Thanks

**Comment by whummer** [comment]
Hi @rgoodwin , thanks for the question. The `cdklocal` script is really just a tiny wrapper over the `cdk` command line - so yes, it should also work with CDK projects using Python. Can you perhaps share a few details about your use case, or a small sample, so we can take a closer look and verify that it deploys properly? Thanks!

**Comment by dominikschubert** [comment]
To answer the original question (again): Yes it should work with python :+1:  There's now also a GitHub action that verifies this
