### ISSUE TITLE
Unable To Deploy To Localstack

### ISSUE THREAD

**Issue by jts-mjanda** [localstack/aws-cdk-local#65]
aws-cdk: 1.149.0
aws-cdk-local: 1.65.8

Running the command results in the below: npx cdklocal synth --app bin/EWXCloud.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@aws-cdk/cloudformation-diff'
Require stack:
- E:\EWXDev\webscraping\node_modules\aws-cdk\lib\util\tables.js
- E:\EWXDev\webscraping\node_modules\aws-cdk\lib\util\index.js
- E:\EWXDev\webscraping\node_modules\aws-cdk\lib\settings.js
- E:\EWXDev\webscraping\node_modules\aws-cdk\lib\context-providers\index.js
- E:\EWXDev\webscraping\node_modules\aws-cdk\lib\plugin.js
- E:\EWXDev\webscraping\node_modules\aws-cdk\lib\api\aws-auth\credential-plugins.js
- E:\EWXDev\webscraping\node_modules\aws-cdk\lib\api\aws-auth\sdk-provider.js
- E:\EWXDev\webscraping\node_modules\aws-cdk-local\bin\cdklocal
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\EWXDev\webscraping\node_modules\aws-cdk\lib\util\tables.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\EWXDev\\webscraping\\node_modules\\aws-cdk\\lib\\util\\tables.js',
    'E:\\EWXDev\\webscraping\\node_modules\\aws-cdk\\lib\\util\\index.js',
    'E:\\EWXDev\\webscraping\\node_modules\\aws-cdk\\lib\\settings.js',
    'E:\\EWXDev\\webscraping\\node_modules\\aws-cdk\\lib\\context-providers\\index.js',
    'E:\\EWXDev\\webscraping\\node_modules\\aws-cdk\\lib\\plugin.js',
    'E:\\EWXDev\\webscraping\\node_modules\\aws-cdk\\lib\\api\\aws-auth\\credential-plugins.js',
    'E:\\EWXDev\\webscraping\\node_modules\\aws-cdk\\lib\\api\\aws-auth\\sdk-provider.js',
    'E:\\EWXDev\\webscraping\\node_modules\\aws-cdk-local\\bin\\cdklocal'
  ]
}

A few other points:
Regular non cdklocal deployments are working fine
Downgrading aws-cdk to 1.145.0 resolves this issue with cdklocal

**Comment by jts-mjanda** [comment]
[Problem.65.zip](https://github.com/localstack/aws-cdk-local/files/8381773/Problem.65.zip)
[Working.65.zip](https://github.com/localstack/aws-cdk-local/files/8381774/Working.65.zip)

Attached are 2 sample projects. The sole difference between them is the version of aws-cdk. I've used the latest which is now 1.150.0 (in the 1.x series). The project is a simple deployment of 1 dynamodb table and 1 lambda function.

**Comment by dominikschubert** [comment]
Thanks. Please just update your aws-cdk-local dependency to ^2.15.0. That should fix the issue you're seeing.

You can check out the PR here: https://github.com/localstack/aws-cdk-local/pull/60 if you're interested in why this was breaking with newer aws-cdk versions.

**Comment by jts-mjanda** [comment]
Is it compatible with 1.x AWS-CDK?

**Comment by dominikschubert** [comment]
> Is it compatible with 1.x AWS-CDK?

Yes the packaging seems to be changed in both 1.x and 2.x for aws-cdk, so there should be no difference in this regard
