### ISSUE TITLE
Environment aws://00000000000/eu-central-1 failed bootstrapping: UnknownEndpoint: Inaccessible host: `localhost' at port `4566'. This service may not be available in the `eu-central-1' region.

### ISSUE THREAD

**Issue by merowinger92** [localstack/aws-cdk-local#78]
I get the above error message despite having credentials and localstack running. I can access it in the browser normally.

Doing some research hints from a similar issue with `serverless-localstack`existed and is already solved: https://github.com/localstack/serverless-localstack/issues/125

A workaround is setting `LOCALSTACK_HOSTNAME=127.0.0.1`before using cdklocal.

It was solved with following pull request: [LOCALSTACK_HOSTNAME=127.0.0.1](https://github.com/localstack/serverless-localstack/pull/205)

My system is a M1 MacOS 13.1.

**Comment by whummer** [comment]
Fixed via #79 👍 Thanks!
