### ISSUE TITLE
Incompatibility with aws-cdk >= 2.167.0

### ISSUE THREAD

**Issue by dominikschubert** [localstack/aws-cdk-local#95]
Due to a change in the used JavaScript AWS SDK from v2 to v3, newer `aws-cdk` versions (`2.167.0`) are currently incompatible and will produce an error like this:

```
 ❌  Environment aws://000000000000/us-east-1 failed bootstrapping: InvalidClientTokenId: The security token included in the request is invalid.
...
```

We're working on a fix to make newer versions compatible with LocalStack.
In the meantime the last compatible version of aws-cdk is `2.166.0`.

We'll update the issue here once this has been resolved!

**Comment by pistachionet** [comment]
Same issue for here, this is the error that gets reproduced. 
```
 ❌  Environment aws://000000000000/us-east-1 failed bootstrapping: Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:216:20) {
```
Downgrading aws-cdk to aws-cdk@2.166.0 works as mentioned in the bug title. 

`npm install -g aws-cdk-local aws-cdk@2.166.0
`

**Comment by dominikschubert** [comment]
We've published an updated version to NPM now. Please upgrade to `aws-cdk-local>=2.19.0` for support for `aws-cdk` versions `>=2.167.0`
